#spring.application.name=Backend
#spring.mongodb.uri=mongodb://localhost:27017/CloudShare
#
#spring.data.mongodb.auto-index-creation=true
##for making the uniqueness  true
#
#server.servlet.context-path=/api/v1.0
#spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
#
#
#VITE_CLERK_PUBLISHABLE_KEY=

#clerk.jwks-url=
#clerk.webhook.secret=